<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-76O6G7C" failures="2" tests="2" name="Default test(failed)" time="0.132" errors="0" timestamp="2022-08-03T19:03:56 IST">
  <testcase classname="teatng.Sample3" name="test5" time="0.03">
    <failure type="java.lang.AssertionError" message="This test is failed">
      <![CDATA[java.lang.AssertionError: This test is failed
at teatng.Sample3.test5(Sample3.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="teatng.Sample3" name="test1" time="0.006">
    <failure type="java.lang.AssertionError" message="This test is failed">
      <![CDATA[java.lang.AssertionError: This test is failed
at teatng.Sample3.test1(Sample3.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="teatng.Sample3" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="teatng.Sample3" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase classname="teatng.Sample3" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
